package org.sanjose.web.layout;

import org.sanjose.web.VasjaLoginForm;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

public class LoginLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private VasjaLoginForm vasjaLoginForm_1;
	@AutoGenerated
	private Label label;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public VasjaLoginForm getVasjaLoginForm_1() {
		return vasjaLoginForm_1;
	}

	public void setVasjaLoginForm_1(VasjaLoginForm vasjaLoginForm_1) {
		this.vasjaLoginForm_1 = vasjaLoginForm_1;
	}

	public Label getLabel() {
		return label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel
		panel = buildPanel();
		mainLayout.addComponent(panel);
		mainLayout.setComponentAlignment(panel, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("600px");
		panel.setHeight("200px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel.setContent(verticalLayout_1);
		
		return panel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// label
		label = new Label();
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Vicariato San Jose Del Amazonas");
		label.setSizeUndefined();
		label.setStyleName(Reindeer.LABEL_H2);
		verticalLayout_1.addComponent(label);
		verticalLayout_1.setComponentAlignment(label, new Alignment(48));
		
		// vasjaLoginForm_1
		vasjaLoginForm_1 = new VasjaLoginForm();
		vasjaLoginForm_1.setImmediate(false);
		vasjaLoginForm_1.setWidth("-1px");
		vasjaLoginForm_1.setHeight("-1px");
		verticalLayout_1.addComponent(vasjaLoginForm_1);
		verticalLayout_1.setComponentAlignment(vasjaLoginForm_1, new Alignment(
				48));
		
		return verticalLayout_1;
	}

}
