package org.sanjose.web.layout;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class MesCerradoLayout extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mesCerradoHorizontalLayout;
	@AutoGenerated
	private Button mesCerradoButton;
	@AutoGenerated
	private TextField mesAcerrarField;
	@AutoGenerated
	private Label mesClabel;	
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public Button getMesCerradoButton() {
		return mesCerradoButton;
	}

	public TextField getMesAcerrarField() {
		return mesAcerrarField;
	}

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MesCerradoLayout() {
		mesCerradoHorizontalLayout = buildMesCerradoHorizontalLayout();
		setCompositionRoot(mesCerradoHorizontalLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMesCerradoHorizontalLayout() {
		// common part: create layout
		mesCerradoHorizontalLayout = new HorizontalLayout();
		mesCerradoHorizontalLayout.setImmediate(false);
		mesCerradoHorizontalLayout.setWidth("-1px");
		mesCerradoHorizontalLayout.setHeight("-1px");
		mesCerradoHorizontalLayout.setMargin(true);
		mesCerradoHorizontalLayout.setSpacing(true);
		
		// mesClabel
		mesClabel = new Label();
		mesClabel.setImmediate(false);
		mesClabel.setWidth("-1px");
		mesClabel.setHeight("-1px");
		mesClabel.setValue("Mes a cerrar: ");
		mesCerradoHorizontalLayout.addComponent(mesClabel);
		mesCerradoHorizontalLayout
			.setComponentAlignment(mesClabel, new Alignment(48));
		
		// textField_1
		
		mesAcerrarField = new TextField();
		mesAcerrarField.setEnabled(false);
		mesAcerrarField.setImmediate(false);
		mesAcerrarField.setWidth("-1px");
		mesAcerrarField.setHeight("-1px");
		mesAcerrarField.setSecret(false);
		mesCerradoHorizontalLayout.addComponent(mesAcerrarField);
		mesCerradoHorizontalLayout
			.setComponentAlignment(mesAcerrarField, new Alignment(48));
	
		// mesCerradoButton
		mesCerradoButton = new Button();
		mesCerradoButton.setCaption("Cerrar");
		mesCerradoButton.setImmediate(false);
		mesCerradoButton.setWidth("-1px");
		mesCerradoButton.setHeight("-1px");
		mesCerradoButton.setIcon(new ThemeResource("../icons/close-icon.png"));
		mesCerradoHorizontalLayout.addComponent(mesCerradoButton);
		mesCerradoHorizontalLayout
		.setComponentAlignment(mesCerradoButton, new Alignment(48));

		return mesCerradoHorizontalLayout;
	}

}
