ALTER TABLE OPERACION ADD COLUMN BENEFICIARIO_ID BIGINT, ADD COLUMN CENTROCOSTO_ID BIGINT, ADD COLUMN TIPODOCUMENTO_ID BIGINT;
ALTER TABLE OPERACION ADD CONSTRAINT FK_OPERACION_BENEFICIARIO_ID FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIO (ID)
ALTER TABLE OPERACION ADD CONSTRAINT FK_OPERACION_CENTROCOSTO_ID FOREIGN KEY (CENTROCOSTO_ID) REFERENCES CENTROCOSTO (ID)
ALTER TABLE OPERACION ADD CONSTRAINT FK_OPERACION_TIPODOCUMENTO_ID FOREIGN KEY (TIPODOCUMENTO_ID) REFERENCES TIPODOCUMENTO (ID)


ALTER TABLE `BENEFICIARIO` ADD COLUMN `NOMBRECOMPLETO`
VARCHAR(255) NULL  AFTER `NOMBRE` , ADD COLUMN `DNI` VARCHAR(45) NULL
AFTER `NOMBRECOMPLETO` , ADD COLUMN `TELEFONO` VARCHAR(45) NULL  AFTER
`DNI` , ADD COLUMN `DETALLE` VARCHAR(500) NULL  AFTER `TELEFONO` ,
CHANGE COLUMN `NOMBRE` `NOMBRE` VARCHAR(150) CHARACTER SET 'utf8'
COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL  ;