package org.sanjose.vasja.samples;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CajaManejoUI extends VerticalLayout {
	protected HorizontalLayout horizontalFechas;
	protected DateField fechaDesde;
	protected DateField fechaHasta;
	protected Grid gridCaja;
	protected HorizontalLayout horizontalSaldos;
	protected VerticalLayout verticalSaldoInicial;
	protected Grid gridSaldoInicial;
	protected VerticalLayout verticalSaldoFinal;
	protected Grid gridSaldoFInal;
	protected VerticalLayout verticalButtons;
	protected Button btnEnviar;
	protected Button btnReporteCaja;

	public CajaManejoUI() {
		Design.read(this);
	}
}
