package org.sanjose.vasja.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ComprobanteUI extends VerticalLayout {
	protected VerticalLayout editarComprobante;
	protected HorizontalLayout horizontalProyectoTercero;
	protected ComboBox selProyecto;
	protected ComboBox selTercero;
	protected TextField nombreTercero;
	protected TextField saldoProyPEN;
	protected TextField saldoProyUSD;
	protected TextField saldoProyEUR;
	protected VerticalLayout verticalDetalles;
	protected HorizontalLayout horizontalMonedaCaja;
	protected OptionGroup selMoneda;
	protected ComboBox selCaja;
	protected TextField saldoCajaPEN;
	protected TextField saldoCajaUSD;
	protected HorizontalLayout horizontalFechaVoucher;
	protected PopupDateField dataFechaComprobante;
	protected TextField numVoucher;
	protected HorizontalLayout horizontalIngresoGlosa;
	protected TextField ingreso;
	protected TextField egreso;
	protected TextField glosa;
	protected HorizontalLayout horizontalIngresoGlosa2;
	protected ComboBox selResponsable;
	protected ComboBox selLugarGasto;
	protected VerticalLayout verticalDocumento;
	protected HorizontalLayout horizontalFechaVoucher2;
	protected ComboBox selCodAuxiliar;
	protected ComboBox selTipoDoc;
	protected TextField serieDoc;
	protected TextField numDoc;
	protected PopupDateField fechaDoc;
	protected HorizontalLayout horizontalIngresoGlosa3;
	protected ComboBox selTipoMov;
	protected ComboBox selCtaContable;
	protected ComboBox selRubroInst;
	protected ComboBox selRubroProy;
	protected ComboBox selFuente;
	protected VerticalLayout verticalButtons;
	protected HorizontalLayout horizontalButtons;
	protected Button anularBtn;
	protected Button guardarBtn;

	public ComprobanteUI() {
		Design.read(this);
	}
}
