package org.sanjose.web.layout;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;

public class ReporteCajaBancosLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button printButton;
	@AutoGenerated
	private HorizontalLayout horizontalLayout;
	@AutoGenerated
	private Label reportLabel;
	private OptionGroup formatOptionGroup;
	private OptionGroup reportTypeGroup;
	List<String> formats = Arrays.asList(new String[] { "PDF", "HTML", "XLS" });
	List<String> reportType = Arrays.asList(new String[] { "Simple", "Detallado" });
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ReporteCajaBancosLayout() {
		buildMainLayout();

		formatOptionGroup.setCaption("Formato");
		formatOptionGroup.setContainerDataSource(toContainer(formats));
		formatOptionGroup.select("PDF");
		
		reportTypeGroup.setCaption("Tipo de reporte");
		reportTypeGroup.setContainerDataSource(toContainer(reportType));
		reportTypeGroup.select("Detallado");
		
		setCompositionRoot(mainLayout);
	}
	
	public Container toContainer(List<String> list) {
		Container c = new IndexedContainer();
		if (list!=null) {
			for (final Iterator<?> i = list.iterator(); i.hasNext();) {
            c.addItem(i.next());
			}
		}
		return c;
    }	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// reportLabel
		reportLabel = new Label();
		reportLabel.setImmediate(false);
		reportLabel.setWidth("-1px");
		reportLabel.setHeight("-1px");
		reportLabel.setValue("");
		mainLayout.addComponent(reportLabel);
		mainLayout.setComponentAlignment(reportLabel, new Alignment(48));
		
		// horizontalLayout
		horizontalLayout = buildHorizontalLayout();
		mainLayout.addComponent(horizontalLayout);
		mainLayout.setComponentAlignment(horizontalLayout, new Alignment(48));
		
		// printButton
		printButton = new Button();
		printButton.setCaption("Ver reporte");
		printButton.setImmediate(false);
		printButton.setWidth("-1px");
		printButton.setHeight("-1px");
		printButton.setIcon(new ThemeResource("../icons/window_text.png"));		
		mainLayout.addComponent(printButton);
		mainLayout.setComponentAlignment(printButton, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		horizontalLayout = new HorizontalLayout();
		horizontalLayout.setImmediate(false);
		horizontalLayout.setWidth("-1px");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setMargin(false);
		
		
		// formatOptionGroup
		formatOptionGroup = new OptionGroup();
		formatOptionGroup.setImmediate(false);
		formatOptionGroup.setWidth("-1px");
		formatOptionGroup.setHeight("-1px");
		horizontalLayout.addComponent(formatOptionGroup);
		horizontalLayout.setComponentAlignment(formatOptionGroup,
				new Alignment(48));
		
		// reportTypeGroup
		reportTypeGroup= new OptionGroup();
		reportTypeGroup.setImmediate(false);
		reportTypeGroup.setWidth("-1px");
		reportTypeGroup.setHeight("-1px");
		horizontalLayout.addComponent(reportTypeGroup);
		horizontalLayout.setComponentAlignment(reportTypeGroup,
						new Alignment(68));
				
		
		return horizontalLayout;
	}

	public Button getPrintButton() {
		return printButton;
	}

	public void setPrintButton() {
		mainLayout.removeComponent(printButton);
		printButton = new Button();
		printButton.setCaption("Ver reporte");
		printButton.setImmediate(false);
		printButton.setWidth("-1px");
		printButton.setHeight("-1px");
		printButton.setIcon(new ThemeResource("../icons/window_text.png"));
		mainLayout.addComponent(printButton);
		mainLayout.setComponentAlignment(printButton, new Alignment(48));
	}

	public OptionGroup getReportTypeGroup() {
		return reportTypeGroup;
	}

	public void setReportTypeGroup(OptionGroup reportTypeGroup) {
		this.reportTypeGroup = reportTypeGroup;
	}
	public OptionGroup getFormatOptionGroup() {
		return formatOptionGroup;
	}

	public void setFormatOptionGroup(OptionGroup formatOptionGroup) {
		this.formatOptionGroup = formatOptionGroup;
	}
	public Label getReportLabel() {
		return reportLabel;
	}

	public void setReportLabel(Label reportLabel) {
		this.reportLabel = reportLabel;
	}

}
