package org.sanjose.web.layout;

import java.util.Date;

import org.sanjose.util.ConfigurationUtil;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.VerticalLayout;

public class ReporteCuentaLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button printButton;
	@AutoGenerated
	private HorizontalLayout horizontalLayout;
	@AutoGenerated
	private PopupDateField fechaMaxField;
	@AutoGenerated
	private PopupDateField fechaMinField;
	@AutoGenerated
	private Label reportLabel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ReporteCuentaLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// reportLabel
		reportLabel = new Label();
		reportLabel.setImmediate(false);
		reportLabel.setWidth("-1px");
		reportLabel.setHeight("-1px");
		reportLabel.setValue("Label");
		mainLayout.addComponent(reportLabel);
		mainLayout.setComponentAlignment(reportLabel, new Alignment(48));
		
		// horizontalLayout
		horizontalLayout = buildHorizontalLayout();
		mainLayout.addComponent(horizontalLayout);
		mainLayout.setComponentAlignment(horizontalLayout, new Alignment(48));
		
		// printButton
		printButton = new Button();
		printButton.setCaption("Ver reporte");
		printButton.setImmediate(false);
		printButton.setWidth("-1px");
		printButton.setHeight("-1px");
		printButton.setIcon(new ThemeResource("../icons/window_text.png"));		
		mainLayout.addComponent(printButton);
		mainLayout.setComponentAlignment(printButton, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		horizontalLayout = new HorizontalLayout();
		horizontalLayout.setImmediate(false);
		horizontalLayout.setWidth("-1px");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setMargin(false);
		
		// fechaMinField
		fechaMinField = new PopupDateField();
		fechaMinField.setCaption("Del: ");
		fechaMinField.setImmediate(false);
		fechaMinField.setWidth("-1px");
		fechaMinField.setHeight("-1px");
		fechaMinField.setInvalidAllowed(false);
		fechaMinField.setValue(ConfigurationUtil.getBeginningOfMonth(new Date()));
		fechaMinField.setRequired(true);
		fechaMinField.setResolution(4);
		horizontalLayout.addComponent(fechaMinField);
		horizontalLayout
				.setComponentAlignment(fechaMinField, new Alignment(48));
		
		// fechaMaxField
		fechaMaxField = new PopupDateField();
		fechaMaxField.setValue(new Date());
		fechaMaxField.setCaption("Al:");
		fechaMaxField.setImmediate(false);
		fechaMaxField.setWidth("-1px");
		fechaMaxField.setHeight("-1px");
		fechaMaxField.setInvalidAllowed(false);
		fechaMaxField.setRequired(true);
		fechaMaxField.setResolution(4);
		horizontalLayout.addComponent(fechaMaxField);
		horizontalLayout
				.setComponentAlignment(fechaMaxField, new Alignment(48));
		
		return horizontalLayout;
	}

	public Button getPrintButton() {
		return printButton;
	}

	public void setPrintButton() {
		mainLayout.removeComponent(printButton);
		printButton = new Button();
		printButton.setCaption("Ver reporte");
		printButton.setImmediate(false);
		printButton.setWidth("-1px");
		printButton.setHeight("-1px");
		printButton.setIcon(new ThemeResource("../icons/window_text.png"));
		mainLayout.addComponent(printButton);
		mainLayout.setComponentAlignment(printButton, new Alignment(48));
	}

	public PopupDateField getFechaMaxField() {
		return fechaMaxField;
	}

	public void setFechaMaxField(PopupDateField fechaMaxField) {
		this.fechaMaxField = fechaMaxField;
	}

	public PopupDateField getFechaMinField() {
		return fechaMinField;
	}

	public void setFechaMinField(PopupDateField fechaMinField) {
		this.fechaMinField = fechaMinField;
	}

	public Label getReportLabel() {
		return reportLabel;
	}

	public void setReportLabel(Label reportLabel) {
		this.reportLabel = reportLabel;
	}

}
